#!/usr/bin/env bash

# Symbolically link to all of the dot files in this directory from the
# home directory.

cd $(dirname $0) || exit $?

for file in $(pwd)/.*; do
    name=$(basename $file)  
    case $name in
        .|..|.git)
            :
            ;;
        *)
            /bin/ln -i -s ${file#~/} ~/$name || exit $?
            ;;
    esac
done

