#!/usr/bin/env bash

# Symbolically link to all of the dot files in this directory from the home
# directory. Chain in more git configuration layers.

cd $(dirname $0) || exit $?
if [ -d /mnt/c/windows ]; then
  git config --global include.path ~/.dot/git/wsl.gitconfig
else
  git config --global include.path ~/.dot/git/unix.gitconfig
fi

for file in .*; do
    case $file in
        .|..|.git*)
            :    
            ;;
        *)
            if [ -e ~/$file ]; then
                echo "warning: ~/$file already exists, not overwriting"
            else
                ln -i -s -v $(pwd)/$file ~/$file || exit $?
            fi
        ;;
    esac
done